<?= $head ?>
	<!-- Navbar -->
    <?= $navbar ?> 
	<!-- SideBar -->
	<?= $aside ?>
	<!-- PreContent -->
	<?= $preContent ?>
	<!-- Content -->
	<?= $content ?>
	<!-- AfetContent -->
	<?= $afterContent ?>
	<!-- Footer -->
<?= $footer ?>